name: Build and Deploy to Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@stable

      # Using the demoparser2 dependency via NPM causes some issues, just submodule it and local build instead
      - name: Build demoparser
        run: |
          cargo install wasm-pack
          cd submodules/demoparser2/src/wasm
          wasm-pack build --out-dir www/pkg --target no-modules
          cd ../../../../
          node ./scripts/fix.js

      - name: Build website
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
